# Generated by Django 4.1.3 on 2022-11-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='im')),
                ('name1', models.CharField(max_length=300)),
                ('desc1', models.TextField()),
            ],
        ),
    ]
